/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_200715324;

/**
 *
 * @author ayau1_000
 */
public class Pantalla1 extends javax.swing.JFrame {

    /**
     * Creates new form pantalla1
     */
    public Pantalla1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_planta = new javax.swing.JButton();
        jbtn_zombis = new javax.swing.JButton();
        jbtn_comenzar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setText("Plantas vs Zombies Guatemalteco");

        jbtn_planta.setText("Jugador Plantas");
        jbtn_planta.setName("btn_plantas"); // NOI18N
        jbtn_planta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_plantaMouseClicked(evt);
            }
        });
        jbtn_planta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_plantaActionPerformed(evt);
            }
        });

        jbtn_zombis.setText("Jugador Zombis");
        jbtn_zombis.setName("btn_zombis"); // NOI18N
        jbtn_zombis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_zombisMouseClicked(evt);
            }
        });
        jbtn_zombis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_zombisActionPerformed(evt);
            }
        });

        jbtn_comenzar.setText("Comenzar Juego");
        jbtn_comenzar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_comenzar.setMaximumSize(new java.awt.Dimension(150, 23));
        jbtn_comenzar.setMinimumSize(new java.awt.Dimension(150, 23));
        jbtn_comenzar.setName("btn_comenzar"); // NOI18N
        jbtn_comenzar.setPreferredSize(new java.awt.Dimension(150, 23));

        jbtn_eliminar.setText("Eliminar Datos");
        jbtn_eliminar.setMaximumSize(new java.awt.Dimension(150, 23));
        jbtn_eliminar.setMinimumSize(new java.awt.Dimension(150, 23));
        jbtn_eliminar.setName("btn_eliminar"); // NOI18N
        jbtn_eliminar.setPreferredSize(new java.awt.Dimension(150, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbtn_comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn_planta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_zombis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_planta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_zombis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_comenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_plantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_plantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_plantaActionPerformed

    private void jbtn_zombisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_zombisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_zombisActionPerformed

    private void jbtn_plantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_plantaMouseClicked
        // TODO add your handling code here:
        System.out.println("Click en Boton Planta");
        int tipo = 0;
        PantallaJugador pjP = new PantallaJugador(tipo);
        pjP.setVisible(true);
    }//GEN-LAST:event_jbtn_plantaMouseClicked

    private void jbtn_zombisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_zombisMouseClicked
        // TODO add your handling code here:
        System.out.println("Click en Boton Zombi");
        int tipo = 1;
        PantallaJugador pjZ = new PantallaJugador(tipo);
        pjZ.setVisible(true);
    }//GEN-LAST:event_jbtn_zombisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn_comenzar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_planta;
    private javax.swing.JButton jbtn_zombis;
    // End of variables declaration//GEN-END:variables
}
